title: La Profeto
author: Kahlil Gibran (trad. via Ivan Torbey)
language: eo
date: 2025-05-15
publisher: Publikigita libere ĉe GitHub
rights: MIT
description: Traduko de The Prophet en Esperanto
subject: Poezio, Filozofio, Vivo, Amo
